name: Run Django Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Set up Docker Compose
      run: |
        docker-compose up -d postgres redis rabbitmq  # Start necessary services
        docker-compose run be poetry run python manage.py test  # Run the Django tests

    - name: Clean up
      run: |
        docker-compose down  # Stop and remove containers, networks, volumes
